apiVersion: v1
kind: ReplicationController
metadata:
  name: example-app
spec:
  replicas: 3
  selector:
    app: example-app
  template:
    metadata:
      name: example-app
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: aidamina/example-app:v1
        ports:
        - containerPort: 3030